version: "3.7"
services:
    swagger-ui:
        image: swaggerapi/swagger-ui
        container_name: "swagger-ui"
        ports:
            - '${SWAGGER_PORT}:8080'
        volumes:
            - ./doc:/usr/share/nginx/html/doc
        environment:
            API_URL: doc/api.yaml

    postgres:
        build: ./database/
        container_name: "postgres"
        restart: unless-stopped
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./db-data:/var/lib/postgresql/data
        command: ["postgres", "-c", "log_statement=all", "-c", "logging_collector=on"]

volumes:
    db-data:
        driver: local