version: "3.7"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
        - "80:8080"
    volumes:
        - ./doc:/usr/share/nginx/html/doc
    environment:
        API_URL: doc/api.yaml