version: "3.7"
services:
    swagger-ui:
        image: swaggerapi/swagger-ui
        container_name: "swagger-ui"
        ports:
            - "80:8080"
        volumes:
            - ./doc:/usr/share/nginx/html/doc
        environment:
            API_URL: doc/api.yaml
        networks:
            - user-defined

    app:
        build: .
        container_name: "app"
        depends_on:
            - postgres
        ports:
            - ${PORT}:${PORT}
        networks:
            - user-defined
        environment:
            PORT: ${PORT}

    postgres:
        build: ./database/
        container_name: "postgres"
        restart: always
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - user-defined

volumes:
    db-data:
        driver: local

networks:
    user-defined:
        driver: bridge
        name: 'user-defined'